language: java
env:
  global:
  - secure: WpTpYt2cO1Wt9OfQy5R721MJHdjLqbhT0z4XxNM8nj6oagGXHj+jZwO6DnDV3md46hFLXz3KNhCM88Qyh8kI8YkQhG8NPoX4kg8L46qNc0U3vNoun3uF33BuaCn+sLQQYUYYG8OB0R7T96xhDlxmbH1q4uoiMEtOZTUzOZz1zJly33qRHnIIJ0ua+ipkoxRJtWFtOpCZLRuScQzH4gHaQ+LpBptAzuR6BYNhrMe1HwcIRYJ9ERsLs7jNToruB46GTfKIb3DZ+BBMbeakvpnhjiy7QSl3BaESiTbv9p8iP0ZbuZblZvwu1Fwcoy9GW+TcAOTPPLz4DRBRXMfiN3da467CD9F4zUyB5dsBh7SKc5x3HOxJSLBbBV1GP2vCgUpU/xwwnkwhKXYyl5YsfloAKjntPSKo0Ewr3ojtmttR5dhTIs0gzkFoTKag7OKPiw/8HYifYKy6fVaprESBfO0nKisixI2sq7IrgYt1eIhbGx1J95qdP/hqMg7QfhbwlT7Jr3GdqArWu7XlVr64oiHj6LcWLLbArw8drZIQznaGkGkpsTxU/HDwfp3Tx7kyLfmE+32oNOxMis4K9tW5t2RW3hEi+Fjyublx09oH/w45itJIRud/h6MwWybAX5oqnzHMc6NObhiHKmJP7WMouTI9nQ4/ElpTXWKt8PvR9vAfTFU=
  - secure: idsq1IMxQq6K3WE+g8EO3jLSHsMwsIwvelwVNMtOu2ZMqsFwKVefzDDAU/ToelYYsRCTHEQgrwn/tq8KNQP1+e1D/TyW4taAscQOPXIloG2a3Itra0QW83rWAaD7aAJ8kSm1WD7iwxOKH3Ey683ImvuLxf+oq+HASZXoPQai3GDV8FGi1awVWwYGD7GlXIlwgsERcguwK60dwawlLmFtbNJ/+fQonc/7mDU7Gtxo31lT/tz4+cZXLlbBSl5MS5IcqLJm2K5G7D5OkK3wI23jdfaQ52OpNkJTtmxoxos+Q0y+FQoLQ3GdjLppzJwuEVIpim9bU3E/rKRJyTAQ0E+xvrca3VNr0Y9ja30qWAFEvfXGBpr9BLyZaLGH2owU3GQRdzLggvaqdJieoYAbEB05/JIn/DjlaKq/KK4O6AHY/V4XGz3EH1iuwODC72UtPmoeaFBe5+BIL9EEt9IjcdlNNshmadClU+Azq7LhM6qqiwGkKvgGr4inGbN4ElVM948ysPV9jM1PLGcqskuk13brJfUA3rl5fF5yS8mAy4Zt9oLG/Rp08PV/8T8ewcajfRhd/Az3E6mRomYr09GwGaDvSNS1TNXhJqMoCv7TTgk1slh4Ye+QRs6tQsC+YtcjSqoU03LwVXbf3GEKOI6X8s75txbdHcA3r9QmSJ/4CD8mE+w=
  sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
script:
  - mvn clean package
after_script:
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  - "./build-and-push-all.sh"
