# PRS Travis file.
# Author: Antoine Aubé (aube.antoine@protonmail.com)

language: java

env:
  global:
  - BRANCH=$TRAVIS_BRANCH
  - secure: VSmL8Kwl5rD1SD37qYbesrD6Z64lJZ7sUZE0SCzWkL718g7oTcf6/frlwFM+dHqwK+wBd6BJv724hOb090dVzB8kvy7fMc+s/fecQOMBIad5H33tx/AYtzXjJv55qC3yDQCVBXaHpUf/wc22n0AFkAXNqSR+75ydRfbvIMXfYPVmOHIrrTa3tk4xI3hw2RBAMM0PcZwol58TkxeM+WK2OsDcrz5NLfiGHAISxK+0e+bMSAR2E0UNFr7DMaxb6KAm+66wzBZ4BBAIHassLiCBrEmBdxnfWz9vtGlvc+GrEV9k2ux0/sYb2GNCHIFXHqrBn8QBIgUGwV2wt0T3zktX6wa2SjcWE0jg36rswT0ggsRljF0d+zee1fvTFI60CMV4bkRpLaPOOfA9l4MTMdD5zplxWNPw0NP4FABKyOI+Pqg0lY1HfuZkGa05SSzj9jbZ+AaY+PYo1lTHSOakVbOuM5ajQsx7lfvqu8UdrmnTJTPboKlEWkvlYuNZwndEhVeLVRFsEer5lOFIJGmNHsbyU5V+1EaUsSWd012dDvPzc5kN/EY8Aa7fGnDsup6ap1wxDD63Z3pf7zF3uOd7ruvQ8+P3Uvec1EhodEUy1aH3slHSSMrF9N7rGk4ZML1dFVxDgEPLBQtS0BhA7oRu6Bwl1skAbBAMaxEImJAay+qn/tc=
  - secure: fy+Fnv4vk0Vnwh9ET3uEVQMqjtozfdutrcGvPnhGCg8mNPPjrYuvSwUe3xdqkYIa4rjIGwP4MqzC+MXajmvSCd4sUZw0XNWG80oyESSKi0fMGksY0RARzf9Cu+T30HGjHDV2caFGdgLQbA2XARje/bp0e2d4F5iI2zYVbg2YGb+JrqtKP3G6sOzQ8pH1PcQZEZP7cQ5u2QQGaV6BSHzCUbwHzbvqhJ0kVy0cRh4ZxwMRblY7HTRczkM8SagC9a8DklIHJ1/XTlkeDEJaTWNoBTeeZWcZuVFKV6MhH2l/1KpVSSwx3OFCpdyFRKwrpcsXeJAoUgpV43/NlhT2gaM9Vd1+6PSIChF3cZCPEJRh+j9mt8sh8Yn6BaG4hRUx3JNzrQMGy8z3W1dhQKs6t0sYfrZJHPJayRTi5VGDPIRqxWU5LWg6P7v+cIFzcilaqwtcv6d+42jCcAaZy6XXQAshaizE7NZ3hBEEzHEy4JW4Abi3kTelL0KDGXEM2TNsH7STss65owgeyxo5ZO8fKSAXBlYLdUIpJJKFFhdPqfE7/YVsRVi0aaZJSKldGMCcQNa/ZHaFncyRgTCTAP2ABZVvYCJ3aWWsc731165wxZQQxcmkmlZAhv+xDvdkACq70/IcuihnIgUz35u9QcLUDFnDlqvmwVPTsadx0QuGJOE/oSY=
  - secure: Ir1uTdhlvrgRTvCyb8tQw8f4meUP7eOODvpbSDqnwMPOO0Jj2bZm7o+HNFGo82z8klgpol9JzQtAFcjwB52X3FKLBv5K7pH6exR67iGSKl5/A3z9gRk4o4DmnPd2LHICJgFShdH86ZL6WvxTus2PqdStg8dJx90j4aisvjR3g9/j2kNpYeUW3Y9q7j4wrILh0FL+W9OhqFnxzqCBg4MSU3ZyjYtAICzLtaxqlVXcHZHokAIXPxZfUqfOBfUblK496Cht2JONcHXD8PtrRubuYf9iwb6R8botMX+Cm+KYeFy0tlRGAY3k04JppnNQfcWMAGqZ/O2veoS+Z4RJRTGKIfbPwspSHpKHVbHkgaxlAIp9R6hJqCLcl91nIO+O58KSrWPF4KS2KARZQCbS6JPT7vMKoUsCyJwjyIQShDLdsE2yUe1eFwcWFFCmuMqQHEUWK4VG7puXVvA/6OEyDS8riffCZjon03P4lLjcWdTvVcAQGraoG1YSCjAEdrfvnasbOQmSbwvvCZpjso6wIfocgGmZgYch3qv7KKG+qxhQQkOkreQ3xZspnxpGQ9a8Zm+EoPccvkLq7Vk4kxIFcXHVgxXCyOvSBdtvfvmhlR4kyocTI9dpy9hVAAYrwi1eWX1O3Gd/Azh9KlZ4xx4GpAxT7cSTLaAXIVm67vYWkThFgEQ=

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package

after_script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - ./build-and-push-all.sh