version: '3'

services:
  priorities_database:
    image: postgres
    environment:
      - POSTGRES_USER=al
      - POSTGRES_PASSWORD=pwd

  priorities_webservice:
    image: alteamfive/prs-priorities
    links:
      - priorities_database
    ports:
      - "8080"