version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=al
      - POSTGRES_PASSWORD=pwd

  administration:
    container_name: admin
    image: alteamfive/prs-administration-client
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    links:
      - backend
    stdin_open: true
    tty: true

  driver-A:
    container_name: driverA
    image: alteamfive/prs-driver-client
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - DEFAULT_CAR_TYPE=FIREFIGHTERS
      - DEFAULT_CAR_ID=1
      - DEFAULT_CAR_LONGITUDE=1.0
      - DEFAULT_CAR_LATITUDE=4.0
    links:
      - backend
    stdin_open: true
    tty: true

  driver-B:
    container_name: driverB
    image: alteamfive/prs-driver-client
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - DEFAULT_CAR_TYPE=FIREFIGHTERS
      - DEFAULT_CAR_ID=2
      - DEFAULT_CAR_LONGITUDE=3.0
      - DEFAULT_CAR_LATITUDE=2.0
    links:
      - backend
    stdin_open: true
    tty: true

  driver-C:
    container_name: driverC
    image: alteamfive/prs-driver-client
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - DEFAULT_CAR_TYPE=FIREFIGHTERS
      - DEFAULT_CAR_ID=3
      - DEFAULT_CAR_LONGITUDE=0.0
      - DEFAULT_CAR_LATITUDE=0.0
    links:
      - backend
    stdin_open: true
    tty: true

  driver-D:
    container_name: driverD
    image: alteamfive/prs-driver-client
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - DEFAULT_CAR_TYPE=FIREFIGHTERS
      - DEFAULT_CAR_ID=4
      - DEFAULT_CAR_LONGITUDE=1.0
      - DEFAULT_CAR_LATITUDE=-1.0
    links:
      - backend
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    image: alteamfive/prs-backend
    links:
      - message-bus
      - traffic-conditions
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_CONDITIONS_HOST=traffic-conditions
      - TRAFFIC_CONDITIONS_PORT=9090

  traffic-conditions:
    image: alteamfive/traffic-conditions

  message-bus:
    image: rabbitmq

  traffic-light-one:
    container_name: tl1
    image: alteamfive/prs-tl
    links:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_LIGHT_ID=1
    depends_on:
      - message-bus
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-light.jar"]

  traffic-light-two:
    container_name: tl2
    image: alteamfive/prs-tl
    links:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_LIGHT_ID=2
    depends_on:
      - message-bus
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-light.jar"]

  traffic-light-three:
    container_name: tl3
    image: alteamfive/prs-tl
    links:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_LIGHT_ID=3
    depends_on:
      - message-bus
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-light.jar"]

  traffic-light-four:
    container_name: tl4
    image: alteamfive/prs-tl
    links:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_LIGHT_ID=4
    depends_on:
      - message-bus
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-light.jar"]

  traffic-light-five:
    image: alteamfive/prs-tl
    links:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
      - TRAFFIC_LIGHT_ID=5
    depends_on:
      - message-bus
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-light.jar"]

  traffic-lights-group:
    container_name: tlg
    image: alteamfive/prs-tl-group-orchestration
    links:
      - message-bus
    depends_on:
      - message-bus
    environment:
      - BUS_ADDRESS=message-bus
    command: ["./wait-for-it.sh", "bus-message:15672", "--", "java", "-jar", "./traffic-lights-group-orchestration.jar"]