version: '3'

services:
  priorities_database:
    image: postgres
    environment:
      - POSTGRES_USER=al
      - POSTGRES_PASSWORD=pwd

  priorities_webservice:
    container_name: priorities
    image: alteamfive/prs-priorities
    links:
      - priorities_database
      - administration
    ports:
      - "8080:8080"

  administration:
    container_name: admin
    image: alteamfive/prs-administration-client
    environment:
      - BACKEND_HOST=priorities_webservice
      - BACKEND_PORT=8080
    stdin_open: true
    tty: true