package fr.polytech.al.five.administration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-20T08:17:56.247+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.fr/al/five/administration", name = "AdministrationWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdministrationWebService {

    @WebMethod
    @RequestWrapper(localName = "registerPriority", targetNamespace = "http://www.polytech.fr/al/five/administration", className = "fr.polytech.al.five.administration.RegisterPriority")
    @ResponseWrapper(localName = "registerPriorityResponse", targetNamespace = "http://www.polytech.fr/al/five/administration", className = "fr.polytech.al.five.administration.RegisterPriorityResponse")
    public void registerPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.polytech.al.five.administration.CarType arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modifyPriority", targetNamespace = "http://www.polytech.fr/al/five/administration", className = "fr.polytech.al.five.administration.ModifyPriority")
    @ResponseWrapper(localName = "modifyPriorityResponse", targetNamespace = "http://www.polytech.fr/al/five/administration", className = "fr.polytech.al.five.administration.ModifyPriorityResponse")
    public void modifyPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.polytech.al.five.administration.CarType arg0
    );
}
