package fr.polytech.al.five.administration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-20T08:17:56.273+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "AdministrationWebServiceImplementationService", 
                  wsdlLocation = "file:/home/antoine/Polytech/AL/priority-rules-system/administration-client/src/main/resources/wsdl/AdministrationWS.wsdl",
                  targetNamespace = "http://www.polytech.fr/al/five/administration") 
public class AdministrationWebServiceImplementationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.fr/al/five/administration", "AdministrationWebServiceImplementationService");
    public final static QName AdministrationWebServiceImplementationPort = new QName("http://www.polytech.fr/al/five/administration", "AdministrationWebServiceImplementationPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/antoine/Polytech/AL/priority-rules-system/administration-client/src/main/resources/wsdl/AdministrationWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdministrationWebServiceImplementationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/antoine/Polytech/AL/priority-rules-system/administration-client/src/main/resources/wsdl/AdministrationWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationWebServiceImplementationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AdministrationWebServiceImplementationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AdministrationWebService
     */
    @WebEndpoint(name = "AdministrationWebServiceImplementationPort")
    public AdministrationWebService getAdministrationWebServiceImplementationPort() {
        return super.getPort(AdministrationWebServiceImplementationPort, AdministrationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationWebService
     */
    @WebEndpoint(name = "AdministrationWebServiceImplementationPort")
    public AdministrationWebService getAdministrationWebServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(AdministrationWebServiceImplementationPort, AdministrationWebService.class, features);
    }

}
