
package fr.polytech.al.five;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdministrationWebService", targetNamespace = "http://webservices.five.al.polytech.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministrationWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyPriority", targetNamespace = "http://webservices.five.al.polytech.fr/", className = "fr.polytech.al.five.ModifyPriority")
    @ResponseWrapper(localName = "modifyPriorityResponse", targetNamespace = "http://webservices.five.al.polytech.fr/", className = "fr.polytech.al.five.ModifyPriorityResponse")
    public void modifyPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        CarType arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerPriority", targetNamespace = "http://webservices.five.al.polytech.fr/", className = "fr.polytech.al.five.RegisterPriority")
    @ResponseWrapper(localName = "registerPriorityResponse", targetNamespace = "http://webservices.five.al.polytech.fr/", className = "fr.polytech.al.five.RegisterPriorityResponse")
    public void registerPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        CarType arg0);

}
