
package fr.polytech.al.five;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdministrationWebServiceImplementationService", targetNamespace = "http://implementations.webservices.five.al.polytech.fr/", wsdlLocation = "http://localhost:8080/priority-rules-backend/webservices/AdministrationWS?wsdl")
public class AdministrationWebServiceImplementationService
    extends Service
{

    private final static URL ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://implementations.webservices.five.al.polytech.fr/", "AdministrationWebServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/priority-rules-backend/webservices/AdministrationWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public AdministrationWebServiceImplementationService() {
        super(__getWsdlLocation(), ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public AdministrationWebServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationWebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdministrationWebService
     */
    @WebEndpoint(name = "AdministrationWebServiceImplementationPort")
    public AdministrationWebService getAdministrationWebServiceImplementationPort() {
        return super.getPort(new QName("http://implementations.webservices.five.al.polytech.fr/", "AdministrationWebServiceImplementationPort"), AdministrationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationWebService
     */
    @WebEndpoint(name = "AdministrationWebServiceImplementationPort")
    public AdministrationWebService getAdministrationWebServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementations.webservices.five.al.polytech.fr/", "AdministrationWebServiceImplementationPort"), AdministrationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return ADMINISTRATIONWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
